---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: print
  namespace: monitoring
spec:
  friendlyName: K8S print
  url: https://print.${SECRET_DOMAIN_ME}
  type: HTTPS
  httpMethod: GET
  interval: 300
  alertContacts: ${SECRET_UPTIMEROBOTCONTACTS}
