---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: grafana
  namespace: monitoring
spec:
  friendlyName: "K8S grafana"
  url: "https://grafana.${SECRET_DOMAIN_ME}"
  type: HTTPS
  httpMethod: GET
  interval: 300
  alertContacts: "${SECRET_UPTIMEROBOTCONTACTS}"
