apiVersion: v1
kind: Secret
metadata:
    name: phpipam-secret
    namespace: networking
stringData:
    mariadb-password: ENC[AES256_GCM,data:/lfB2EHc345jfsAm8Ipsfnz0NF49bw==,iv:WaHrzA3CNh6UzHFhYjLBoJ0ybCfwI53V7SlB+BCZs7g=,tag:gSOJbhq/cAC9GE9vbX6O+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMHRiSW44elUrTCsrdW5B
            dHdsUUNmT2x2MUtYcXU3bTNmbnRVaUxYR0JBCkEyUUlwSXRGR0RWSnUzVzhzdjBn
            TjJMTHg2WUlFZU5wRnBtdGt2RlZjR0EKLS0tIGRwd1ZUcG9CdTNiZnJBd21qd3pH
            Z1p2UjNzNVlqMDdmbnJ2VzNLbnpSRDgKqOXGIMGh+guklWK6HD2aJY7dvWlYeqh+
            70H8dXdrNQ65dwkj+pQEdupfSMuaG69tg2RvIz17jKNKr7k6BDmQHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T15:28:01Z"
    mac: ENC[AES256_GCM,data:IHgG0EN/CGFY05PyqCMuAFf4RpOyQzFOTe/7pWPezA8sL1jW8dONdj6ymvCLPm4o9ft5IIj9kFfbV+X8mbTqOlaRRDBBaW6oCCeoMlneEF+++RopESNYA8BWxeXRS+gTG0baeFCEkipg/Z+uMKwE1401od6+EtPMv9WdouWzLk0=,iv:HKGONslpD/jbh2Il839D7jrk1p/6D+cGUI4bqQ8BAjI=,tag:bkWeUrpLV8q1FTWKnK9HPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
