apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
stringData:
    address: ENC[AES256_GCM,data:TZfqRT14xU3ekXeBH/OQpRikpDIAiypc1HEj+C3lfmuE+iy0HTGmj1u15hpTlBzFMU0Xt2UtBsn3H8/7y0aBpip2ZRbMt1sb8/mIaYTFBviAKoJoqSrq2J4btXZ7+e3Tarw/3davIwKJ4JJkKDv0P/FpLMlgevjA,iv:Oqk28iujqcY4RbJtZGryIedEY63h1eHIU0LbStmyR+Q=,tag:3K9kTp28I+Z04gRgOq3YiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOGRIQmNTZDJaNUpDbWVq
            bkwvbklvbkRpVE9RQytkeUNWamFsWUFzRzJBCk1qek5ueFBWYUF4NmptRTBqekxr
            VXZDazhreHB6UnhGNXZzMTZwV0xxWkkKLS0tIERUQkhOUEhDellUWjNZRU9WU1Z0
            bWZUWDR1SUwvVnJ1SDAydXV6YS9Db3cKEygUxkjdTZjA9y7i0CHSGdfCrgGOXhp3
            6+67/ce4guTnhNIxux7dOARTg3gjp4lVAbR4SZFkAbEIMOq1JU63aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T19:55:44Z"
    mac: ENC[AES256_GCM,data:yMsh0wsWa4Ng/RMsb/dDgsuags9dlvNMu4do7lh7RCmwRY6AKblJhAMEAQ22G4XSdafuJvOu40TAHEZUipW0ZEXDRLMw7A6DkxdKi/1fL3BTmysLjg/lyAYBM8te8ueCQ7V2refSnXpHIIpDWIXAqsaZLrAluGIrSA1uJ7UHWcI=,iv:+Lf7ynNmSkUP4F+CeNLPHbmysjsKdpQhuoV5ob71w08=,tag:Q02RySxsf2RMKFi9IRtrng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
