---
apiVersion: v1
kind: Service
metadata:
  name: vpn
  labels:
    app.kubernetes.io/name: vpn
spec:
  type: LoadBalancer
  ports:
  - name: vpn-isakmp
    protocol: UDP
    port: 500
    targetPort: 500
  - name: vpn-ike
    protocol: UDP
    port: 4500
    targetPort: 4500
  externalTrafficPolicy: Local
  loadBalancerIP: ${SVC_VPN_ADDRESS}
  selector:
    app.kubernetes.io/name: vpn
