---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: s3gw-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://aquarist-labs.github.io/s3gw-charts/
