---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-jaeger-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: "identity-forward-auth@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hajimari.io/enable: "true"
    hajimari.io/icon: chip
    hajimari.io/appName: Jaeger
spec:
  tls:
    - hosts:
        - "jaeger.${SECRET_DOMAIN_ME}"
      secretName: linkerd-jaeger-tls
  rules:
    - host: "jaeger.${SECRET_DOMAIN_ME}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
