apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:WpkjQPM=,iv:BAmU/q1wHuAuKXssANqwK6Ol8qNV7zmpuXxFw44nyXQ=,tag:nh7u1f3KLkft5DdymPwtTQ==,type:str]
    admin-password: ENC[AES256_GCM,data:mYNyxe1vR2/FiIeW,iv:PTIj5Fs9RCfuT/y59aaaPhSLh559Fqk8wQ67o9TR6AA=,tag:VCmrtXlyFWCKkoG+Fx/QsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOGRIQmNTZDJaNUpDbWVq
            bkwvbklvbkRpVE9RQytkeUNWamFsWUFzRzJBCk1qek5ueFBWYUF4NmptRTBqekxr
            VXZDazhreHB6UnhGNXZzMTZwV0xxWkkKLS0tIERUQkhOUEhDellUWjNZRU9WU1Z0
            bWZUWDR1SUwvVnJ1SDAydXV6YS9Db3cKEygUxkjdTZjA9y7i0CHSGdfCrgGOXhp3
            6+67/ce4guTnhNIxux7dOARTg3gjp4lVAbR4SZFkAbEIMOq1JU63aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T16:15:31Z"
    mac: ENC[AES256_GCM,data:N1GKYclxKIy02s9NhS0sdOS2pFrSJsaKykpn5MM7smh4vVg0DHdGsRiHkCJwXlZ8i6ZtSxiLXK4to1rWbEcKzAYda/yzhfqKOaf8AGXNgf6C9+pHfFERzkZuzp/ReHUjz2N6Hfb/HXK4qH/f2u/SpkXXw9jiqOpfNWleYf+g23k=,iv:FH0nWaol27eD5uzLes8qe8XPR37jtS357nFV5zvDEsQ=,tag:WD78hpikxYUDfvNdE6A37Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
