---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-csi-driver-nfs
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: 'true'
spec:
  path: ./kubernetes/apps/kube-system/csi-driver-nfs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: csi-driver-nfs
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-csi-driver-nfs-sc
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: 'true'
spec:
  path: ./kubernetes/apps/kube-system/csi-driver-nfs/sc
  prune: true
  dependsOn:
    - name: cluster-apps-csi-driver-nfs
  sourceRef:
    kind: GitRepository
    name: k8s-homelab
  healthChecks:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      name: nfs-csi
  interval: 30m
  retryInterval: 1m
  timeout: 5m
