---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litestream-cleanup-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litestream-cleanup-secrets
    template:
      engineVersion: v2
      data:
        s3-endpoint: "{{ index . \"LITESTREAM-HOST\" }}"
        s3-access-key: "{{ index . \"LITESTREAM-ACCESS-KEY\" }}"
        s3-secret-key: "{{ index . \"LITESTREAM-ACCESS-SECRET\" }}"
        s3-region: "{{ index . \"LITESTREAM-REGION\" }}"
  dataFrom:
    - extract:
        key: garage-s3
