---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: development
  labels:
    app: dokuwiki
  name: dokuwiki
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns/is-public: "true"
    external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_TARGET_SKY}"
    traefik.ingress.kubernetes.io/router.middlewares: identity-forward-auth@kubernetescrd
    hajimari.io/enable: "true"
    hajimari.io/icon: "file-document-edit"
spec:
  tls:
    - secretName: "${SECRET_DOMAIN_ME/./-}-tls"
      hosts:
        - wiki.${SECRET_DOMAIN_ME}
  rules:
    - host: wiki.${SECRET_DOMAIN_ME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dokuwiki
                port:
                  number: 80
