---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./prometheus/ks.yaml
  - ./uptimerobot-operator/ks.yaml
  - ./grafana/ks.yaml
  - ./thanos/ks.yaml
  - ./mystrom-exporter/ks.yaml
  - ./github-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./unifi-poller/ks.yaml
