---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/tuppr/main/config/crd/bases/tuppr.home-operations.com_kubernetesupgrades.yaml
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    version: ${KUBERNETES_VERSION}
  healthChecks:
    - apiVersion: v1
      kind: Node
      description: Require Ready nodes before the control plane upgrade
      expr: status.conditions.exists(c, c.type == "Ready" && c.status == "True")
      timeout: 10m
  talosctl:
    image:
      tag: ${TALOS_VERSION}
