---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: keepalived-ingress-vip
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  url: https://github.com/janeczku/keepalived-ingress-vip
  ref:
    branch: master
