apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: vmware-exporter
spec:
  selector:
    matchLabels:
      app: vmware-exporter
  template:
    metadata:
      labels:
        app: vmware-exporter
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: vmware-exporter
          image: "pryorda/vmware_exporter:v0.18.4"
          imagePullPolicy: Always
          ports:
            - containerPort: 9272
              name: metrics
          envFrom:
            - configMapRef:
                name: vmware-exporter-config
            - secretRef:
                name: vmware-exporter-secrets
