---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - changedetection.io
  - mealie
  - octoprint
  - paperless
  # - wallabag
  - hajimari
  - longhorn-system
