---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - code-server/ks.yaml
  - drop/ks.yaml
  - echo-server/ks.yaml
  - hajimari/ks.yaml
  - octoprint/ks.yaml
  # - s3gw/ks.yaml
  - sharry/ks.yaml
  - webtrees/ks.yaml
