---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aquasecurity.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./codecentric.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./gitlab.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./k8up.yaml
  - ./kubernetes-sigs-nfd-charts.yaml
  - ./kyverno-charts.yaml
  - ./loft-charts.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./mittwald-charts.yaml
  - ./neuvector.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./postgres-operator.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./synology-csi.yaml
  - ./vmware-tanzu-charts.yaml
  - ./weave-gitops.yaml
