---
collections:
  - name: community.general
    version: 6.5.0
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.1
  - name: robertdebock.roles
    version: 1.10.6
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1
  # - src: frzk.chrony
  #   version: 2.0.0
  - src: idiv-biodiversity.systemd_timesyncd
    version: v1.2.0
