# (string) Timezone for the servers
timezone: "Europe/Zurich"
system_timezone: "{{ timezone }}"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:
ansible_user: pi

kubeconfig_target: "/Users/tdeutsch/iCloudDrive/Allgemein/kubectl/homelab.yaml"
