---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: linkding-secrets
    template:
      engineVersion: v2
      data:
        litestream-s3-access-key-id: "{{ index . \"LITESTREAM-ACCESS-KEY\" }}"
        litestream-s3-secret-access-key: "{{ index . \"LITESTREAM-ACCESS-SECRET\" }}"
        litestream-s3-endpoint: "{{ index . \"LITESTREAM-HOST\" }}"  # inkl. Protokoll (http:// oder https://)
        litestream-s3-bucket: "litestream"
        litestream-age-pubkey: "{{ .LITESTREAM_AGE_PUBKEY }}"
        litestream-age-secret: "{{ .LITESTREAM_AGE_SECRET }}"

  dataFrom:
    - extract:
        key: litestream-age
    - extract:
        key: garage-s3
