---
kubernetes:
  children:
    master:
      hosts:
        tpi-node1:
          ansible_host: 192.168.8.111
        tpi-node2:
          ansible_host: 192.168.8.112
        tpi-node3:
          ansible_host: 192.168.8.113
    worker:
      hosts:
        tpi-node4:
          ansible_host: 192.168.8.114
# nfs-server:
#   hosts: tpi-node3
