---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calibre-ingress.yaml
  - gaps-ingress.yaml
  - lldap-ingress.yaml
  - sabnzbd-ingress.yaml
  - prowlarr-ingress.yaml
  - radarr-ingress.yaml
  - sonarr-ingress.yaml
  - notifiarr-ingress.yaml
