---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-exporter
  namespace: media
  labels:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter
  ports:
    - name: monitoring
      port: 9487
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tautulli-exporter
  namespace: media
  labels:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli-exporter
      app.kubernetes.io/instance: tautulli-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tautulli-exporter
  namespace: media
  labels:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli-exporter
      app.kubernetes.io/instance: tautulli-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli-exporter
        app.kubernetes.io/instance: tautulli-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: monitoring
    spec:
      containers:
        - name: tautulli-exporter
          image: ghcr.io/tuxpeople/tautulli-exporter:0.1.0
          imagePullPolicy: Always
          env:
            - name: SERVE_PORT
              value: '9487'
            - name: TAUTULLI_URI
              value: ${SECRET_TAUTULLI_URL}
            - name: TAUTULLI_API_KEY
              value: ${SECRET_TAUTULLI_API_KEY}
          ports:
            - name: monitoring
              containerPort: 9487
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
