---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap_v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: Europe/Zurich
  MAIN_SC: iscsi-delete

  # Auth
  AUTH_SUBDOMAIN: auth

  # Ingress
  INGRESS_CLASS_INTERNAL: internal
  INGRESS_CLASS_EXTERNAL: external

  # TLS
  SECRET_TLS_CERT: "${SECRET_DOMAIN/./-}-production-tls"

  # Cert-Manager
  CERT_ISSUER: letsencrypt-production

  # SMTP
  SMTP_RELAY_HOST: smtp.utils.svc.cluster.local
  SMTP_RELAY_PORT: "25"
