---
- include: locale.yml
  tags:
    - locale

- include: packages.yml
  tags:
    - packages

- include: network.yml
  tags:
    - network

- include: filesystem.yml
  tags:
    - filesystem

- include: user.yml
  tags:
    - user

# - include: longhorn.yml
#   tags:
#     - longhorn

# - name: Reboot
#   reboot:
#   throttle: 1
