---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: productivity
components:
  - ../../components/common
resources:
  - ./code-server/ks.yaml
  - ./freshrss/ks.yaml
  - ./hajimari/ks.yaml
  - ./linkding/ks.yaml
  - ./obsidian/ks.yaml
  - ./paperless/ks.yaml
