---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: pv-backup
    files:
      - scripts/pv-backup.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  - rbac.yaml
  - pv-backup-cron.yaml
  - volumes.yaml
