---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: echo-server
  namespace: monitoring
spec:
  friendlyName: "K8S echo-server"
  url: "https://echo-server.${SECRET_DOMAIN_ME}"
  type: HTTPS
  httpMethod: GET
  interval: 300
  alertContacts: "${SECRET_UPTIMEROBOTCONTACTS}"
