---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: &name gatus-internal
  annotations:
    policies.kyverno.io/title: Generate gatus endpoints
    policies.kyverno.io/category: Monitoring
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      This policy will automatically generate gatus endpoints for
      all Ingresses with the ingressClassName set to internal.
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  generateExisting: true
  rules:
    - name: *name
      match:
        any:
          - resources:
              kinds:
                - Ingress
      exclude:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - test
          - resources:
              kinds:
                - Ingress
              annotations:
                gatus.io/enabled: "false"
      preconditions:
        all:
          - key: "{{ request.object.spec.ingressClassName }}"
            operator: Equals
            value: internal
      context:
        - name: GATUS_HOST
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/host" || request.object.spec.rules[0].host }}'
            jmesPath: "to_string(@)"
        - name: GATUS_NAME
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/name" || request.object.metadata.name }}'
            jmesPath: "to_string(@)"
        - name: GATUS_PATH
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/path" || request.object.spec.rules[0].http.paths[0].path }}'
            jmesPath: "to_string(@)"
        - name: GATUS_STATUS_CODE
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/status-code" || `200` }}'
            jmesPath: "to_string(@)"
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: "{{ request.object.metadata.name }}-gatus-ep"
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          kind: ConfigMap
          metadata:
            labels:
              gatus.io/enabled: "true"
          data:
            config.yaml: |-
              ---
              endpoints:
                - name: {{ GATUS_NAME }}
                  group: internal-kubernetes
                  url: https://{{ GATUS_HOST }}{{ GATUS_PATH }}
                  interval: 2m
                  client:
                    dns-resolver: tcp://192.168.13.1:53
                  conditions:
                    - "[STATUS] == {{ GATUS_STATUS_CODE }}"
                  alerts:
                    - type: discord
