---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage
    template:
      engineVersion: v2
  data:
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: arr-apis
        property: RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: arr-apis
        property: SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: arr-apis
        property: PROWLARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: arr-apis
        property: SABNZBD_API_KEY
    - secretKey: HOMEPAGE_VAR_OVERSEERR_API_KEY
      remoteRef:
        key: arr-apis
        property: OVERSEERR_API_KEY
    - secretKey: HOMEPAGE_VAR_TAUTULLI_API_KEY
      remoteRef:
        key: arr-apis
        property: TAUTULLI_API_KEY
    - secretKey: HOMEPAGE_VAR_PAPERLESS_API_KEY
      remoteRef:
        key: paperless
        property: PAPERLESS_API_KEY
  dataFrom:
    - extract:
        key: homepage
