apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: monitoring
  labels:
    alertmanagerConfig: discord
spec:
  route:
    groupBy: ['alertname']
    groupInterval: 10s
    groupWait: 1s
    repeatInterval: 30s
    receiver: discord
    routes:
      - matchers:
          - namespace: "*"
  receivers:
    - name: discord
      webhookConfigs:
        - url: 'http://alertmanager-discord:9094'
