---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-discord-address.sops.yaml
  # - alertmanager-discord-config.yaml
  - alertmanager-discord-deployment.yaml
  - alertmanager-discord-service.yaml
