---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Mise"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # once a week
jobs:
  mise:
    name: upgrade-tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache mise tools
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.local/share/mise
          key: mise-${{ runner.os }}-${{ hashFiles('.mise.toml') }}

      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upgrade dependencies
        run: mise upgrade --bump

      - name: Get diff of .mise.toml
        run: |
          git diff > diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch;
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "$GITHUB_OUTPUT";
          {
              echo "### Diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "$GITHUB_STEP_SUMMARY";
          rm diff.patch

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          branch: "mise-upgrade-dependencies"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

            > [!TIP]
            > Merge this pull request and then run `mise upgrade --bump` on your workstation.
