---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Mise"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # once a week
jobs:
  mise:
    name: upgrade-tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Cache mise tools
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.local/share/mise
          key: mise-${{ runner.os }}-${{ hashFiles('.mise.toml') }}

      - name: Setup mise
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upgrade dependencies
        run: mise upgrade --bump

      - name: Get diff of .mise.toml
        run: |
          git diff > diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch;
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "$GITHUB_OUTPUT";
          {
              echo "### Diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "$GITHUB_STEP_SUMMARY";
          rm diff.patch

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          branch: "mise-upgrade-dependencies"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

            > [!TIP]
            > Merge this pull request and then run `mise upgrade --bump` on your workstation.
